"""Emit a JS module with translation-schema constants from vtkjs_translator.

The Python translator (``trame_vtklocal.module.vtkjs_translator``) drives the
server-side scene shape. The push-sync JS-oracle dump runs in the browser and
walks live ``synchronizerContext`` instances; it must mirror translator skip
lists, class-name mapping, dependency relations, and array-extraction config.

Static lookup tables live in ``vtkjs_translator`` as module-level dicts/sets.
Imperative special cases (polydata field-array extraction, mapper input list
handling, camera property allowlist, renderer background-alpha merge,
light-type integer-to-string) are *not* in the schema; the JS dump handles
those inline with comments referencing the corresponding Python source.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PYTHON_SOURCE = REPO_ROOT / "src" / "trame_vtklocal" / "module" / "vtkjs_translator.py"


def load_translator():
    spec = importlib.util.spec_from_file_location(
        "vtkjs_translator_for_schema", PYTHON_SOURCE
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _normalize_relations(raw):
    out = {}
    for vtk_type, relations in raw.items():
        out[vtk_type] = {}
        for prop, spec in relations.items():
            if isinstance(spec, dict):
                out[vtk_type][prop] = {
                    "method": spec["method"],
                    "collectionType": spec.get("collection_type"),
                    "indexed": bool(spec.get("indexed", False)),
                }
            else:
                method, collection_type = spec
                out[vtk_type][prop] = {
                    "method": method,
                    "collectionType": collection_type,
                    "indexed": False,
                }
    return out


def _polydata_arrays(raw):
    return {
        key: {
            "registration": meta["registration"],
            "vtkClass": meta["vtkClass"],
        }
        for key, meta in raw.items()
    }


def build_schema():
    t = load_translator()
    return {
        "classNameMap": dict(t.CLASS_NAME_MAP),
        "collectionTypes": sorted(t.COLLECTION_TYPES),
        "skipTypes": sorted(t.SKIP_TYPES),
        "propertyRelations": _normalize_relations(t.PROPERTY_RELATIONS),
        "attributeRegistrations": dict(t.ATTRIBUTE_REGISTRATIONS),
        "fieldDataGetters": dict(t.FIELD_DATA_GETTERS),
        "polydataArrays": _polydata_arrays(t.POLYDATA_ARRAYS),
        "skipProperties": sorted(t.SKIP_PROPERTIES),
        "renderWindowSkipProperties": sorted(t.RENDERWINDOW_SKIP_PROPERTIES),
        "rendererSkipProperties": sorted(t.RENDERER_SKIP_PROPERTIES),
        "lookupTableSkipProperties": sorted(t.LOOKUPTABLE_SKIP_PROPERTIES),
        "mapperSkipProperties": sorted(t.MAPPER_SKIP_PROPERTIES),
        "propertySkipProperties": sorted(t.PROPERTY_SKIP_PROPERTIES),
        "cameraProperties": sorted(t.CAMERA_PROPERTIES),
        "vtkDataTypeMap": {str(k): v for k, v in t.VTK_DATATYPE_MAP.items()},
        "vtkLightTypeMap": {str(k): v for k, v in t.VTK_LIGHT_TYPE_MAP.items()},
        "classToDataType": dict(t.CLASS_TO_DATATYPE),
    }


HEADER = """\
// AUTO-GENERATED by vue-components/scripts/gen_translation_schema.py.
// Do not edit by hand. Run `npm run gen-schema` to regenerate.
//
// Source of truth: src/trame_vtklocal/module/vtkjs_translator.py
//
// This module mirrors only the *static* lookup tables of the Python
// translator. Imperative translation logic (polydata field-array extraction,
// mapper input handling, camera property allowlist application, renderer
// background-alpha merge, light-type integer-to-string) is implemented in
// JavaScript inline and references its Python counterpart by comment.
"""


def emit_js(schema: dict) -> str:
    parts = [HEADER, ""]

    def emit_const(name, value, kind="object"):
        if kind == "set":
            payload = json.dumps(value, indent=2)
            parts.append(f"export const {name} = new Set({payload});\n")
        else:
            payload = json.dumps(value, indent=2)
            parts.append(f"export const {name} = {payload};\n")

    emit_const("CLASS_NAME_MAP", schema["classNameMap"])
    emit_const("COLLECTION_TYPES", schema["collectionTypes"], kind="set")
    emit_const("SKIP_TYPES", schema["skipTypes"], kind="set")
    emit_const("PROPERTY_RELATIONS", schema["propertyRelations"])
    emit_const("ATTRIBUTE_REGISTRATIONS", schema["attributeRegistrations"])
    emit_const("FIELD_DATA_GETTERS", schema["fieldDataGetters"])
    emit_const("POLYDATA_ARRAYS", schema["polydataArrays"])
    emit_const("SKIP_PROPERTIES", schema["skipProperties"], kind="set")
    emit_const(
        "RENDERWINDOW_SKIP_PROPERTIES",
        schema["renderWindowSkipProperties"],
        kind="set",
    )
    emit_const(
        "RENDERER_SKIP_PROPERTIES",
        schema["rendererSkipProperties"],
        kind="set",
    )
    emit_const(
        "LOOKUPTABLE_SKIP_PROPERTIES",
        schema["lookupTableSkipProperties"],
        kind="set",
    )
    emit_const(
        "MAPPER_SKIP_PROPERTIES", schema["mapperSkipProperties"], kind="set"
    )
    emit_const(
        "PROPERTY_SKIP_PROPERTIES",
        schema["propertySkipProperties"],
        kind="set",
    )
    emit_const("CAMERA_PROPERTIES", schema["cameraProperties"], kind="set")
    emit_const("VTK_DATATYPE_MAP", schema["vtkDataTypeMap"])
    emit_const("VTK_LIGHT_TYPE_MAP", schema["vtkLightTypeMap"])
    emit_const("CLASS_TO_DATATYPE", schema["classToDataType"])

    parts.append("export function mapClassName(className) {\n")
    parts.append("  return CLASS_NAME_MAP[className] || className;\n")
    parts.append("}\n")

    return "".join(parts)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="output .js path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if --out is out-of-date instead of writing",
    )
    args = parser.parse_args(argv)

    schema = build_schema()
    js = emit_js(schema)

    out_path = Path(args.out)
    if args.check:
        if not out_path.exists():
            print(f"{out_path} does not exist; run `npm run gen-schema`.", file=sys.stderr)
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != js:
            print(
                f"{out_path} is out-of-date with vtkjs_translator.py; "
                "run `npm run gen-schema`.",
                file=sys.stderr,
            )
            return 1
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(js, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
